name: Deployment Exercise 1
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
      - name: Lint code
        run: |
          echo "Linting code..."
          npm run lint
      - name: Run tests
        run: |
          echo "Running tests..."
          npm test
      - name: Build project
        run: |
          echo "Building project..."
          npm run build
      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          # Simulate deployment
          echo "Deployment successful!"